config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",
                                                   registrations: "users/registrations",
                                                   passwords: "users/passwords" }

  devise_for :shelters, path: 'shelters', controllers: { sessions: "shelters/sessions",
                                                         registrations: "shelters/registrations",
                                                         passwords: "shelters/passwords" }

  root to: 'pets#index'

  resources :shelters, only: [] do
    resources :pets, controller: 'shelters/pets'
  end

  resources :pets, only: [:index, :show]
end

app/models/pet.rb
class Pet < ApplicationRecord
  BOOLEAN_OPTIONS = { 'Tak' => true, 'Nie' => false, 'Nie wiadomo' => nil }.freeze

  enum sex: %w[samiec samica].freeze
  enum size: %w[mały średni duży].freeze
  enum species: %w[kot pies].freeze

  belongs_to :shelter

  has_one_attached :image

  validates :name, :sex, :breed, :species, presence: true
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pet = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    # tempolary solution
    shelter = Shelter.find_or_create_by!(name: "Schronisko", address: "Ul",
      phone_number: "531 519 111")
    @pet = shelter.pets.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(
      :image, :name, :sex, :birth_date, :breed, :species, :size,
      :registry_id, :age_info, :description, :children_friendly,
      :allergic_friendly, :dog_friendly, :cat_friendly, :sterilized,
      :microchipped
    )
  end
end

app/controllers/shelters/pets_controller.rb
module Shelters
  class PetsController < ApplicationController
    def index; end
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
        <ul>
          <% pet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class = "container">
    <div class = "row">
      <div class="col-auto">
        <div class="form-group">
          <%= form.file_field :image %>
        </div>
      </div>
     </div>

        <div class="form-row align-items-center">
          <div class="col-auto">
          
            <div class="form-group">
              <%= form.label 'Imię' %>
              <%= form.text_field :name, :class=>"form-control" %>
            </div>

            <div class="form-group">
              <%= form.label 'Płeć' %>
              <%= form.select(:sex, Pet.sexes.keys, include_blank: true, :class=>"form-control") %>
            </div>

            <div class="form-group">
              <%= form.label 'Rok urodzenia' %>
              <%= form.number_field :birth_date, :class=>"form-control" %>
            </div>

            <div class="form-group">
              <%= form.label 'Wiek' %>
              <%= form.text_field :age_info, :class=>"form-control" %>
            </div>

            <div class="form-group">
              <%= form.label 'Rasa' %>
              <%= form.text_field :breed, :class=>"form-control" %>
            </div>

            <div class="form-group">
              <%= form.label 'Gatunek' %>
              <%= form.select(:species, Pet.species.keys, include_blank: true) %>
            </div>

            <div class="form-group">
              <%= form.label 'Wielkość' %>
              <%= form.select(:size, Pet.sizes.keys, include_blank: true) %>
            </div>

            <div class="form-group">
              <%= form.label 'Numer ewidencyjny' %>
              <%= form.text_field :registry_id, :class=>"form-control" %>
            </div>

            <div class="form-group">
              <%= form.label 'Opis' %>
              <%= form.text_area :description, :class=>"form-control" %>
            </div>

            <div class="form-group">
              <%= form.label 'Przyjazny dla dzieci' %>
              <%= form.select(:children_friendly, Pet:: BOOLEAN_OPTIONS, include_blank: true) %>
            </div>

            <div class="form-group">
              <%= form.label 'Toleruję psy' %>
              <%= form.select(:dog_friendly, Pet:: BOOLEAN_OPTIONS, include_blank: true) %>
            </div>

            <div class="form-group">
              <%= form.label 'Toleruje koty' %>
              <%= form.select(:cat_friendly, Pet:: BOOLEAN_OPTIONS, include_blank: true) %>
            </div>

            <div class="form-group">
              <%= form.label 'Dla alergików' %>
              <%= form.select(:allergic_friendly, Pet:: BOOLEAN_OPTIONS, include_blank: true) %>
            </div>

            <div class="form-group">
              <%= form.label 'Sterylizacja/kastracja' %>
              <%= form.select(:sterilized, Pet:: BOOLEAN_OPTIONS, include_blank: true) %>
            </div>

            <div class="form-group">
              <%= form.label 'Oczipowany' %>
              <%= form.select(:microchipped, Pet:: BOOLEAN_OPTIONS, include_blank: true) %>
            </div>

        </div>
      </div> 
        <button type="submit" class="btn btn-primary">Zatwierdź</button>
<% end %>

app/views/pets/edit.html.erb
<h1>Edycja danych zwierzaka</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |

<div class="container">
  <%= link_to 'Back', pets_path %>
</div>

app/views/pets/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">OCELOT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#zwierzeta">Zwierzęta<span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#schroniska">Schroniska<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>

  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Szukaj</button>
  </form>

  <div class="btn-group">
    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Zaloguj się
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <%= link_to "Użytkownik", new_user_session_path, class:"dropdown-item", role: "button"%> 
      <span class="sr-only">(current)</span></a>
      <%= link_to "Schronisko", new_shelter_session_path, class:"dropdown-item", role: "button" %> 
      <span class="sr-only">(current)</span></a>
    </div>
  </div>
</nav>

<div class="jumbotron">
  <h1 class="display-4">OCELOT</h1>
  <p class="lead">Znajdź swojego zwierza!</p>
  <p class="lead">Załóż konto, jako indywidualny użytkownik albo schronisko.</p>
  <%= link_to "Zarejestruj się jako użytkownik", new_user_registration_path, class:"btn btn-light btn-lg", role: "button" %> 
  <%= link_to "Zarejestruj schronisko", new_shelter_registration_path, class: "btn btn-light btn-lg", role: "button" %> 
</div>

<div data-spy="scroll" data-target="#navbar-example2" data-offset="0">
  <a class="dropdown-item" id="zwierzeta"><h4>Zwierzęta</h4></a>
</div>

<div class="card-deck">
  <div class="card shadow-sm">
    <img src="https://images.unsplash.com/photo-1507984211203-76701d7bb120?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1652&q=80" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Kitku</h5>
    </div>

    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">samiec</li>
      <li class="list-group-item">kot</li>
    </ul>

    <div class="card-body">
      <a href="#" class="btn btn-primary">Zobacz zwierza</a>
    </div>
  </div>

  <div class="card shadow-sm">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTApZLoQvpqAcM8zAciA8Xwol-OOM6jdsPSfDLO2LD82jc63m2z" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Ocelot</h5>
    </div>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">samiec</li>
      <li class="list-group-item">ocelot</li>
    </ul>

    <div class="card-body">
      <a href="#" class="btn btn-primary">Zobacz zwierza</a>
    </div>
  </div>

  <div class="card shadow-sm">
    <img src="https://images.unsplash.com/photo-1507146426996-ef05306b995a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Pieseł</h5>
    </div>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">samiec</li>
      <li class="list-group-item">pies</li>
    </ul>
    <div class="card-body">
      <a href="#" class="btn btn-primary">Zobacz zwierza</a>
    </div>
  </div>
</div>

<div data-spy="scroll" data-target="#navbar-example2" data-offset="0">
  <a class="dropdown-item" id="schroniska"><h4>Schroniska</h4></a>
</div>

<div class="card-deck">
  <div class="card mb-3 shadow-sm" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="http://schronisko.kalisz.pl/wp-content/uploads/2018/06/schronisko_logo.png" class="card-img" alt="logo">
      </div>
      <div class="card-body">
        <h5 class="card-title">Schronisko3</h5>
        <button type="button" class="btn btn-secondary btn-sm">Zobacz</button>
      </div>
    </div>
  </div>
  <div class="card mb-3 shadow-sm" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="http://schronisko.kalisz.pl/wp-content/uploads/2018/06/schronisko_logo.png" class="card-img" alt="logo">
      </div>
      <div class="card-body">
        <h5 class="card-title">Schronisko3</h5>
        <button type="button" class="btn btn-secondary btn-sm">Zobacz</button>
      </div>
    </div>
  </div>

  <div class="card mb-3 shadow-sm" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="http://schronisko.kalisz.pl/wp-content/uploads/2018/06/schronisko_logo.png" class="card-img" alt="logo">
      </div>
      <div class="card-body">
        <h5 class="card-title">Schronisko3</h5>
        <button type="button" class="btn btn-secondary btn-sm">Zobacz</button>
      </div>
    </div>
  </div>
</div>

app/views/pets/new.html.erb
<h1>Dodaj zwierza</h1>

<%= render 'form', pet: @pet %>

<div class="container">
  <%= link_to 'Back', pets_path %>
</div>

app/views/pets/show.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col">
      <div class= "image_pets" >
        <%= image_tag(@pet.image) %>
      </div>
    </div>
  </div>
  <div class = "row">
    <div class = "col">
  <p>
    <strong>Name:</strong>
    <%= @pet.name %>
  </p>

<p>
  <strong>Sex:</strong>
  <%= @pet.sex %>
</p>

<p>
  <strong>Species:</strong>
  <%= @pet.species %>
</p>

<p>
  <strong>birth_date:</strong>
  <%= @pet.birth_date %>
</p>

<p>
  <strong>Age info:</strong>
  <%= @pet.age_info %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Children friendly:</strong>
  <%= @pet.children_friendly %>
</p>

<p>
  <strong>Allergic friendly:</strong>
  <%= @pet.allergic_friendly %>
</p>

<p>
  <strong>Dog friendly:</strong>
  <%= @pet.dog_friendly %>
</p>

<p>
  <strong>Cat friendly:</strong>
  <%= @pet.cat_friendly %>
</p>

<p>
  <strong>Sterilized:</strong>
  <%= @pet.sterilized %>
</p>

<p>
  <strong>Microchipped:</strong>
  <%= @pet.microchipped %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |

<div class="container">
  <%= link_to 'Back', pets_path %>
</div>